import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const epilogue = localFont({
  src: [
    {
      path: "../public/fonts/Epilogue/static/Epilogue-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Epilogue/static/Epilogue-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/Epilogue/static/Epilogue-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Epilogue/static/Epilogue-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Epilogue/static/Epilogue-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Epilogue/static/Epilogue-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Epilogue/static/Epilogue-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Epilogue/static/Epilogue-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/Epilogue/static/Epilogue-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-epilogue",
});

const hankenGrotesk = localFont({
  src: [
    {
      path: "../public/fonts/Hanken_Grotesk/static/HankenGrotesk-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Hanken_Grotesk/static/HankenGrotesk-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/Hanken_Grotesk/static/HankenGrotesk-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Hanken_Grotesk/static/HankenGrotesk-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Hanken_Grotesk/static/HankenGrotesk-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Hanken_Grotesk/static/HankenGrotesk-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Hanken_Grotesk/static/HankenGrotesk-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Hanken_Grotesk/static/HankenGrotesk-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/Hanken_Grotesk/static/HankenGrotesk-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-hanken-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${epilogue.variable} ${hankenGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
